# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StarBucks_Clone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StarBucks_Clone
  pod "Texture"

  target 'StarBucks_CloneTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StarBucks_CloneUITests' do
    # Pods for testing
  end

end
